#' Extract hazard ratio and confidence intervals from a coxph object
#' @description
#' Convenience function to extract hazard ratio and confidence intervals from a coxph object,
#' as generated by a call to coxph(), comparing survival times between two groups
#'
#' @param coxphData coxph object; coxphData <- coxph(Surv(TTE, Cens) ~ group, data=df)
#'
#' @return a vetor contain p value, HR, HR00.5, HR0.95
#' @export
#'
#' @examples getHRandCIfromCoxph(cox.fit)
getHRandCIfromCoxph <- function(coxphData) {

    stopifnot(is(coxphData, "coxph"))

    tmp <- cbind(
        summary(coxphData)$coef[,
                                c("Pr(>|z|)", "exp(coef)"),
                                drop=FALSE],
        summary(coxphData)$conf[,
                                c("lower .95", "upper .95"),
                                drop=FALSE]
    )
    colnames(tmp) <- c("P","HR","CIl0.95","CIu0.95")
    return(tmp)

}
